name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '❗ Breaking Changes:'
    labels:
      - '❗ Breaking Change'
  - title: '🚀 New Features:'
    labels:
      - '✏️ Feature'
  - title: '🐛 Fixes:'
    labels:
      - '☢️ Bug'
  - title: '📚 Documentation:'
    labels:
      - '📒 Documentation'
  - title: '🧹 Updates:'
    labels:
      - '🧹 Updates'
      - '🤖 Dependencies'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - dependabot
  - dependabot[bot]
version-resolver:
  major:
    labels:
      - 'major'
      - '❗ Breaking Change'
  minor:
    labels:
      - 'minor'
      - '✏️ Feature'
  patch:
    labels:
      - 'patch'
      - '📒 Documentation'
      - '☢️ Bug'
      - '🤖 Dependencies'
      - '🧹 Updates'
  default: patch
template: |
    $CHANGES

    ## 🐳 Docker Images
    - `ghcr.io/$OWNER/$REPOSITORY:latest`
    - `ghcr.io/$OWNER/$REPOSITORY:$RESOLVED_VERSION`

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

    Thanks to $CONTRIBUTORS for making this release possible.

autolabeler:
- label: '📒 Documentation'
  matcher:
    title: '\b(docs|doc:|\[doc\]|README|typos|comment|documentation)\b'
- label: '☢️ Bug'
  matcher:
    title: '\b(fix|race|bug|missing|correct)\b'
- label: '🧹 Updates'
  matcher:
    title: '\b(improve|update|update|refactor|deprecated|remove|unused|test)\b'
- label: '🤖 Dependencies'
  matcher:
    title: '\b(bumb|bdependencies)\b'
- label: '✏️ Feature'
  matcher:
    title: '\b(feature|feat|create|implement|add)\b'
- label: '🤔 Question'
  matcher:
    title: '\b(question|how)\b'