version: "3.9"
services:
  serge:
    image: ghcr.io/telnetdoogie/serge:latest
    container_name: serge
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      - datadb:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro

volumes:
  datadb:
  weights:
