name: Cleanup PR Docker Images

on:
  pull_request:
    types: [closed]

jobs:
  purge-pr-tagged-image:
    name: Delete pr tagged image from ghcr.io
    if: ${{ contains(fromJSON('["nsarrazin","gaby"]'), github.actor) == true }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.3
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}