name: Cleanup PR Docker Images

on:
  pull_request:
    types: [closed]

jobs:
  purge-pr-tagged-image:
    name: Delete container images from PR's
    if: ${{ contains(fromJSON('["nsarrazin","gaby"]'), github.event.pull_request.user.login) }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: castlabs/get-package-version-id-action@v2.1
        id: version
        with:
          version: "pr-${{ github.event.pull_request.number }}"

      - uses: actions/delete-package-versions@v4
        if: ${{ steps.version.outputs.ids != '' }}
        with:
          package-name: ${{ github.event.repository.name }}
          min-versions-to-keep: 0
          package-version-ids: "${{ steps.version.outputs.ids }}"