name: Cleanup PR tagged images every older than 72 hours

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  package-retention:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: doodlescheduling/package-retention@v1
        name: Delete PR tagged images older than 72 hours
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          age: 72h
          version-match: "pr-\\d+$"
