name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request: # Autolabel PRs
    types: [opened, reopened, unlabeled, synchronize]
  pull_request_target: # Autolabel PRs from forks
    types: [opened, reopened, unlabeled, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: main # default repo branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
