name: Cleanup untagged Docker images

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docker-compose.yml'
      - 'docker-compose.dev.yml'
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/dependabot.yml'

jobs:
  purge-untagged-images:
    name: Delete untagged images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true